---

- name: Create dist directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    recurse: true
  with_items:
    - "{{ tpl_directories }}"

- name: Generate Dockerfiles
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode: 0644
  with_items:
    - "{{ tpl_dockerfiles }}"

- name: Generate Dockerfile dgoss tests
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode:  0644
  with_items:
    - "{{ tpl_docker_tests }}"

...
