---

# https://github.com/google-github-actions/release-please-action#release-types-supported

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

name: 📤 Upload artifacts

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 0

      - name: 🚀 Generate dist files
        run: make generate

      - name: 🗜️ Archive dist files
        run: tar -czvf dist.tar.gz dist

      - name: 📤 Upload release assets
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist.tar.gz"]'

...
